project:
  type: website

website:
  title: "CRI Bioinformatics Workshop"
  navbar:
    tools:
    - icon: twitter
      href: https://twitter.com/CancerResearch
    - icon: github
      menu:
        - text: Source Code
          url:  https://github.com/crigrants/CRI_bioinformatics_workshop
    left:
      - text: "Home"
        file: index.qmd
      - text: "Course"
        file: course.qmd
      - text: "Schedule"
        file: schedule.qmd
      - text: "Authors"
        file: authors.qmd
      - text: "Resources"
        file: resources.qmd
      - text: "Acknowledgements"
        file: acknowledge.qmd
        
  sidebar:
    - title: "Course"
      style: "docked"
      contents: course

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
